In [ ]:
import numpy as np
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from tqdm import tqdm
from random import shuffle
import chess_engine

torch.manual_seed(0)

In [4]:
import chess_engine
import numpy as np

In [2]:
c = chess_engine.GameState()

In [5]:
np.array(c.board)

array([['bR', 'bN', 'bB', 'bQ', 'bK', 'bB', 'bN', 'bR'],
       ['bP', 'bP', 'bP', 'bP', 'bP', 'bP', 'bP', 'bP'],
       ['--', '--', '--', '--', '--', '--', '--', '--'],
       ['--', '--', '--', '--', '--', '--', '--', '--'],
       ['--', '--', '--', '--', '--', '--', '--', '--'],
       ['--', '--', '--', '--', '--', '--', '--', '--'],
       ['wP', 'wP', 'wP', 'wP', 'wP', 'wP', 'wP', 'wP'],
       ['wR', 'wN', 'wB', 'wQ', 'wK', 'wB', 'wN', 'wR']], dtype='<U2')

In [ ]:
class Chess(chess_engine.GameState, chess_engine.Move):
    def __init__(self):
        super().__init__()
        self.RowCount = len(self.board)
        self.ColCount = len(self.board)
        self.action_size = 4672  # 8x8x73 refer to the paper for the reasoning of this
        self.encoding = {'bP':1, 
                         'wP':11, 
                         'bR':2, 
                         'wR':12,
                         'bN':3,
                         'wN':13,
                         'bB':4,
                         'wB':14,
                         'bQ':5,
                         'wQ':15,
                         'bK':6,
                         'wK':16,
                         '--':0,
            }
    
    def get_initial_state(self):
        """creates a numpy matrix of rwos*column of the initial untouched board"""
        encoded_board = np.zeros((self.RowCount, self.ColCount), dtype=int)
        for i in range(self.RowCount):
            for j in range(self.ColCount):
                piece = self.board[i][j]
                encoded_board[i,j] = self.encoding[piece]
        return encoded_board
    
    def get_next_state(self, state):
        if self.PieceMoved[0] == 'w':
            player = 0
        else:
            player = 1
            

In [13]:
chess = Chess()
print(chess.get_initial_state())

[[ 2  3  4  5  6  4  3  2]
 [ 1  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [11 11 11 11 11 11 11 11]
 [12 13 14 15 16 14 13 12]]
